apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wkomd3md4-nodejs 
  janus-idp.io/tekton: wkomd3md4-nodejs
  backstage.io/kubernetes-id: wkomd3md4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wkomd3md4-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  